### PR TITLE
Change the way we import url-search-params to work around an issue with Webpack

### PR DESCRIPTION
**Pull request by cdow**
See this for more details: https://github.com/ungap/url-search-params/issues/8

### CODE REVIEW

**Comment by cdow** [comment]
Yes, I do know you can alias that in webpack.  However, I'm not sure I understand what you are saying.  It sounds backwards to me.  Why would this solution be forcing CJS/ES5 syntax universally?  Isn't it just forcing CJS syntax in this one location where it is already using CJS syntax?

If I do this as a webpack alias, wouldn't that force CJS syntax everywhere in a project?  For example, say I have a project with this library and another library that does the same import with ES6 syntax, and I use a webpack alias.  Won't that break because the other library now has to make use of a CJS import with ES6 syntax?

**Comment by indexzero** [comment]
Answers to individual questions below, but overall when I went back and looked at the `package.json` this package exposes I don't see why this would be necessary since CJS syntax is exposed via `"main"` and `"browser"` targets.

> Yes, I do know you can alias that in webpack. However, I'm not sure I understand what you are saying. It sounds backwards to me. Why would this solution be forcing CJS/ES5 syntax universally? Isn't it just forcing CJS syntax in this one location where it is already using CJS syntax?

It is forcing CJS syntax for this module universally. e.g. if a consumer wished to get the non-CJS syntax here they would have the inverse of the current problem you may be hitting.

What I don't quite grok is that this module exposes both CJS and ESM code (see: [package.json](https://github.com/godaddy/transform-url/blob/master/package.json#L5-L7))

> If I do this as a webpack alias, wouldn't that force CJS syntax everywhere in a project? For example, say I have a project with this library and another library that does the same import with ES6 syntax, and I use a webpack alias. Won't that break because the other library now has to make use of a CJS import with ES6 syntax?

Yes. The alias is universal for your project.

**Comment by indexzero** [comment]
After reviewing the difference between their codebase this is a much safer change than previously thought.

It's not a fully transpiled CJS version. Instead they differ by a single line.

**Comment by cdow** [comment]
Do you have any idea when this will make it out in a release?

**Pull request merged**
